//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiSampleMigrat.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiSampleMigrat.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insufficient data..
        /// </summary>
        internal static string alldataNeeded {
            get {
                return ResourceManager.GetString("alldataNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string emailPH {
            get {
                return ResourceManager.GetString("emailPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write both last names separated by a space.
        ///Eg: Chavez Rivas..
        /// </summary>
        internal static string givenNameTltip {
            get {
                return ResourceManager.GetString("givenNameTltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write both names separated by a space.
        ///Eg: Jese Chavez ..
        /// </summary>
        internal static string nameToolTip {
            get {
                return ResourceManager.GetString("nameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string passwordPH {
            get {
                return ResourceManager.GetString("passwordPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match..
        /// </summary>
        internal static string PasswordsNomatch_ {
            get {
                return ResourceManager.GetString("PasswordsNomatch.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords should match..
        /// </summary>
        internal static string passwordsshouldmatch {
            get {
                return ResourceManager.GetString("passwordsshouldmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permissions are required..
        /// </summary>
        internal static string permissionRequired {
            get {
                return ResourceManager.GetString("permissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remember Me.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        internal static string signin {
            get {
                return ResourceManager.GetString("signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updated profile..
        /// </summary>
        internal static string updatedProfile {
            get {
                return ResourceManager.GetString("updatedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong password..
        /// </summary>
        internal static string wrongPassword {
            get {
                return ResourceManager.GetString("wrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write both last names separated by a space.
        ///Eg: Chavez Rivas..
        /// </summary>
        internal static string wrongWrittenGivenNames {
            get {
                return ResourceManager.GetString("wrongWrittenGivenNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write both names separated by a space.
        ///Eg: Jese Chavez ..
        /// </summary>
        internal static string wrongWrittenNames {
            get {
                return ResourceManager.GetString("wrongWrittenNames", resourceCulture);
            }
        }
    }
}
